version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    build: ./postgresql
    volumes:
      - ./postgresql/dumps:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data/
    command: [ 'postgres', '-c', 'config_file=/etc/postgresql.conf' ]
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
